# Basic Jekyll Configuration
title: KinKinetics
description: A Jekyll-powered website for KinKinetics.
baseurl: "" # Leave empty for local development
url: "http://localhost:4000" # Replace with your site's URL when deploying

# Build Settings
markdown: kramdown
theme: minima

# Permalinks
permalink: pretty
